name: Test and Release

on: push

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  issues: write
  id-token: write

jobs:
  tests:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ">=24.19.0 <25"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"
      - name: Install NPM version specified in package.json
        uses: ./.github/actions/install-npm
      - name: Install dependencies
        run: npm ci --no-audit
      - name: Compile
        run: npx tsc
      - name: Test
        run: npm test
      - name: Semantic release
        run: |
          npm i --no-save semantic-release
          npx semantic-release
